import { Product, StockMovement, SalesData } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    sku: 'CHOC-001',
    name: 'Dark Chocolate Bar',
    currentStock: 12,
    reorderLevel: 50,
    unitPrice: 4.50,
    category: 'Confectionery',
  },
  {
    id: '2',
    sku: 'BEVER-001',
    name: 'Orange Juice (1L)',
    currentStock: 28,
    reorderLevel: 60,
    unitPrice: 3.20,
    category: 'Beverages',
  },
  {
    id: '3',
    sku: 'SNACK-001',
    name: 'Potato Chips (200g)',
    currentStock: 45,
    reorderLevel: 80,
    unitPrice: 2.80,
    category: 'Snacks',
  },
  {
    id: '4',
    sku: 'CANDY-001',
    name: 'Gummy Bears (500g)',
    currentStock: 5,
    reorderLevel: 40,
    unitPrice: 5.99,
    category: 'Confectionery',
  },
  {
    id: '5',
    sku: 'WATER-001',
    name: 'Mineral Water (6-pack)',
    currentStock: 35,
    reorderLevel: 100,
    unitPrice: 2.50,
    category: 'Beverages',
  },
  {
    id: '6',
    sku: 'COOKIE-001',
    name: 'Chocolate Cookies (box)',
    currentStock: 18,
    reorderLevel: 55,
    unitPrice: 3.99,
    category: 'Confectionery',
  },
  {
    id: '7',
    sku: 'NUTS-001',
    name: 'Roasted Almonds (200g)',
    currentStock: 22,
    reorderLevel: 60,
    unitPrice: 7.50,
    category: 'Snacks',
  },
  {
    id: '8',
    sku: 'FRUIT-001',
    name: 'Apple Juice (1L)',
    currentStock: 40,
    reorderLevel: 70,
    unitPrice: 3.75,
    category: 'Beverages',
  },
  {
    id: '9',
    sku: 'CEREAL-001',
    name: 'Corn Flakes (500g)',
    currentStock: 33,
    reorderLevel: 50,
    unitPrice: 4.20,
    category: 'Snacks',
  },
  {
    id: '10',
    sku: 'COFFEE-001',
    name: 'Instant Coffee (100g)',
    currentStock: 8,
    reorderLevel: 45,
    unitPrice: 6.99,
    category: 'Beverages',
  },
];

export const MOCK_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: '1',
    productId: '2',
    sku: 'BEVER-001',
    productName: 'Orange Juice (1L)',
    quantity: 50,
    type: 'purchase',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    notes: 'Supplier: Fresh Beverages Inc.',
  },
  {
    id: '2',
    productId: '3',
    sku: 'SNACK-001',
    productName: 'Potato Chips (200g)',
    quantity: -15,
    type: 'sale',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: '3',
    productId: '1',
    sku: 'CHOC-001',
    productName: 'Dark Chocolate Bar',
    quantity: -8,
    type: 'sale',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: '4',
    productId: '5',
    sku: 'WATER-001',
    productName: 'Mineral Water (6-pack)',
    quantity: 100,
    type: 'purchase',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    notes: 'Restocking for weekly sales',
  },
  {
    id: '5',
    productId: '7',
    sku: 'NUTS-001',
    productName: 'Roasted Almonds (200g)',
    quantity: -3,
    type: 'adjustment',
    timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000),
    notes: 'Damaged units removed',
  },
];

export const MOCK_SALES_DATA: SalesData[] = [
  { productId: '1', last30Days: 45 },
  { productId: '2', last30Days: 120 },
  { productId: '3', last30Days: 80 },
  { productId: '4', last30Days: 15 },
  { productId: '5', last30Days: 250 },
  { productId: '6', last30Days: 65 },
  { productId: '7', last30Days: 35 },
  { productId: '8', last30Days: 95 },
  { productId: '9', last30Days: 50 },
  { productId: '10', last30Days: 22 },
];

export const LOCATIONS = [
  'Ground Floor - Electronics',
  'Ground Floor - Food Court',
  'Level 2 - Fashion',
  'Level 2 - Supermarket',
  'Level 3 - Pharmacy',
  'Warehouse - A',
];
