import { Product, StockMovement, SalesData } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    sku: 'CHOC-001',
    name: 'Dark Chocolate Bar',
    description: 'Premium dark chocolate 70% cocoa',
    currentStock: 12,
    minStock: 20,
    maxStock: 200,
    reorderLevel: 50,
    cost: 2.50,
    unitPrice: 4.50,
    category: 'Confectionery',
    supplier: 'Premium Sweets Inc.',
    location: 'Shelf A-1',
    status: 'active',
    lastRestockDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    profitMargin: 80,
  },
  {
    id: '2',
    sku: 'BEVER-001',
    name: 'Orange Juice (1L)',
    description: 'Fresh orange juice, 100% natural',
    currentStock: 28,
    minStock: 30,
    maxStock: 150,
    reorderLevel: 60,
    cost: 1.80,
    unitPrice: 3.20,
    category: 'Beverages',
    supplier: 'Fresh Beverages Inc.',
    location: 'Shelf B-2',
    status: 'active',
    lastRestockDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    profitMargin: 78,
  },
  {
    id: '3',
    sku: 'SNACK-001',
    name: 'Potato Chips (200g)',
    description: 'Crispy salted potato chips',
    currentStock: 45,
    minStock: 40,
    maxStock: 300,
    reorderLevel: 80,
    cost: 1.50,
    unitPrice: 2.80,
    category: 'Snacks',
    supplier: 'Snack Masters Co.',
    location: 'Shelf C-3',
    status: 'active',
    lastRestockDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    profitMargin: 87,
  },
  {
    id: '4',
    sku: 'CANDY-001',
    name: 'Gummy Bears (500g)',
    description: 'Assorted fruity gummy bears',
    currentStock: 5,
    minStock: 25,
    maxStock: 200,
    reorderLevel: 40,
    cost: 3.50,
    unitPrice: 5.99,
    category: 'Confectionery',
    supplier: 'Sweet Delights Ltd.',
    location: 'Shelf A-2',
    status: 'active',
    lastRestockDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    profitMargin: 71,
  },
  {
    id: '5',
    sku: 'WATER-001',
    name: 'Mineral Water (6-pack)',
    description: 'Purified mineral water bottles',
    currentStock: 35,
    minStock: 50,
    maxStock: 500,
    reorderLevel: 100,
    cost: 1.20,
    unitPrice: 2.50,
    category: 'Beverages',
    supplier: 'Pure Water Co.',
    location: 'Shelf B-1',
    status: 'active',
    lastRestockDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    profitMargin: 108,
  },
  {
    id: '6',
    sku: 'COOKIE-001',
    name: 'Chocolate Cookies (box)',
    description: 'Homestyle chocolate chip cookies',
    currentStock: 18,
    minStock: 30,
    maxStock: 250,
    reorderLevel: 55,
    cost: 2.10,
    unitPrice: 3.99,
    category: 'Confectionery',
    supplier: 'Bakery Classics Ltd.',
    location: 'Shelf A-3',
    status: 'active',
    lastRestockDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    profitMargin: 90,
  },
  {
    id: '7',
    sku: 'NUTS-001',
    name: 'Roasted Almonds (200g)',
    description: 'Lightly salted roasted almonds',
    currentStock: 22,
    minStock: 15,
    maxStock: 150,
    reorderLevel: 60,
    cost: 4.50,
    unitPrice: 7.50,
    category: 'Snacks',
    supplier: 'Nut Traders Inc.',
    location: 'Shelf C-2',
    status: 'active',
    lastRestockDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    profitMargin: 67,
  },
  {
    id: '8',
    sku: 'FRUIT-001',
    name: 'Apple Juice (1L)',
    description: 'Pure pressed apple juice',
    currentStock: 40,
    minStock: 35,
    maxStock: 180,
    reorderLevel: 70,
    cost: 2.10,
    unitPrice: 3.75,
    category: 'Beverages',
    supplier: 'Fresh Beverages Inc.',
    location: 'Shelf B-3',
    status: 'active',
    lastRestockDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    profitMargin: 79,
  },
  {
    id: '9',
    sku: 'CEREAL-001',
    name: 'Corn Flakes (500g)',
    description: 'Crispy toasted corn flakes',
    currentStock: 33,
    minStock: 25,
    maxStock: 200,
    reorderLevel: 50,
    cost: 2.30,
    unitPrice: 4.20,
    category: 'Snacks',
    supplier: 'Grain Mills Corp.',
    location: 'Shelf C-1',
    status: 'active',
    lastRestockDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    profitMargin: 83,
  },
  {
    id: '10',
    sku: 'COFFEE-001',
    name: 'Instant Coffee (100g)',
    description: 'Premium instant coffee blend',
    currentStock: 8,
    minStock: 10,
    maxStock: 100,
    reorderLevel: 45,
    cost: 4.20,
    unitPrice: 6.99,
    category: 'Beverages',
    supplier: 'Coffee Imports Ltd.',
    location: 'Shelf B-4',
    status: 'active',
    lastRestockDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    profitMargin: 66,
  },
];

export const MOCK_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: '1',
    productId: '2',
    sku: 'BEVER-001',
    productName: 'Orange Juice (1L)',
    quantity: 50,
    type: 'purchase',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    notes: 'Supplier: Fresh Beverages Inc.',
  },
  {
    id: '2',
    productId: '3',
    sku: 'SNACK-001',
    productName: 'Potato Chips (200g)',
    quantity: -15,
    type: 'sale',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: '3',
    productId: '1',
    sku: 'CHOC-001',
    productName: 'Dark Chocolate Bar',
    quantity: -8,
    type: 'sale',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: '4',
    productId: '5',
    sku: 'WATER-001',
    productName: 'Mineral Water (6-pack)',
    quantity: 100,
    type: 'purchase',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    notes: 'Restocking for weekly sales',
  },
  {
    id: '5',
    productId: '7',
    sku: 'NUTS-001',
    productName: 'Roasted Almonds (200g)',
    quantity: -3,
    type: 'adjustment',
    timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000),
    notes: 'Damaged units removed',
  },
];

export const MOCK_SALES_DATA: SalesData[] = [
  { productId: '1', last7Days: 10, last30Days: 45, last90Days: 140, last365Days: 540, averageDailySales: 1.5, totalRevenue: 202.5 },
  { productId: '2', last7Days: 28, last30Days: 120, last90Days: 370, last365Days: 1440, averageDailySales: 4, totalRevenue: 384 },
  { productId: '3', last7Days: 18, last30Days: 80, last90Days: 240, last365Days: 960, averageDailySales: 2.67, totalRevenue: 224 },
  { productId: '4', last7Days: 3, last30Days: 15, last90Days: 45, last365Days: 180, averageDailySales: 0.5, totalRevenue: 89.85 },
  { productId: '5', last7Days: 60, last30Days: 250, last90Days: 750, last365Days: 3000, averageDailySales: 8.33, totalRevenue: 625 },
  { productId: '6', last7Days: 14, last30Days: 65, last90Days: 195, last365Days: 780, averageDailySales: 2.17, totalRevenue: 259.35 },
  { productId: '7', last7Days: 8, last30Days: 35, last90Days: 105, last365Days: 420, averageDailySales: 1.17, totalRevenue: 262.5 },
  { productId: '8', last7Days: 22, last30Days: 95, last90Days: 285, last365Days: 1140, averageDailySales: 3.17, totalRevenue: 356.25 },
  { productId: '9', last7Days: 12, last30Days: 50, last90Days: 150, last365Days: 600, averageDailySales: 1.67, totalRevenue: 210 },
  { productId: '10', last7Days: 5, last30Days: 22, last90Days: 66, last365Days: 264, averageDailySales: 0.73, totalRevenue: 153.78 },
];

export const LOCATIONS = [
  'Ground Floor - Electronics',
  'Ground Floor - Food Court',
  'Level 2 - Fashion',
  'Level 2 - Supermarket',
  'Level 3 - Pharmacy',
  'Warehouse - A',
];
